#!/bin/bash
echo "═══════════════════════════════════════════════════════"
echo "  MCP Final Check — Continue"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "1. Continue extension:"
code --list-extensions 2>/dev/null | grep -i continue && echo "  ✅ installed" || echo "  ❌ missing"
echo ""
echo "2. Config file:"
[ -f ~/.continue/config.json ] && echo "  ✅ exists" || echo "  ❌ missing"
echo ""
echo "3. API key:"
node -e "try{const c=require(process.env.HOME+'/.continue/config.json');const k=c.models?.[0]?.apiKey;if(k && !k.includes('YOUR_') && k.length>10){console.log('  ✅ set ('+k.substring(0,12)+'...)')}else{console.log('  ❌ NOT set')}}catch(e){console.log('  ❌ error')}"
echo ""
echo "4. MCP server:"
[ -f /home/cs/mcp-servers/pg_mcp_server.js ] && echo "  ✅ exists" || echo "  ❌ missing"
echo ""
echo "5. MCP syntax:"
node --check /home/cs/mcp-servers/pg_mcp_server.js 2>/dev/null && echo "  ✅ OK" || echo "  ❌ syntax error"
echo ""
echo "6. PostgreSQL:"
DATABASE_URL='postgresql://monitor_ai:monitor_secure_1405@localhost:5432/project_monitor' node -e "const {Pool}=require('/home/cs/mcp-servers/node_modules/pg');const p=new Pool({connectionString:process.env.DATABASE_URL});p.query('SELECT 1').then(()=>{console.log('  ✅ reachable');return p.end();}).catch(e=>{console.log('  ❌',e.message)})" 2>/dev/null
echo ""
echo "7. MCP config wired:"
node -e "try{const c=require(process.env.HOME+'/.continue/config.json');console.log('  MCP servers:',Object.keys(c.mcpServers||{}).join(', '))}catch(e){console.log('  ❌ error')}"
echo ""
echo "═══════════════════════════════════════════════════════"
