#!/bin/bash
echo "═══════════════════════════════════════════════════════"
echo "  Continue — 4 گام تا MCP"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "گام ۱ — API Key بگیر:"
echo "  OpenRouter:   https://openrouter.ai/keys"
echo "  Anthropic:    https://console.anthropic.com/settings/keys"
echo "  OpenAI:       https://platform.openai.com/api-keys"
echo ""
echo "گام ۲ — ذخیره کن:"
echo "  bash ~/semantic_core/factory/scripts/set_openrouter.sh sk-or-v1-XXXX"
echo "  یا: bash ~/semantic_core/factory/scripts/set_anthropic.sh sk-ant-XXXX"
echo "  یا تعاملی: bash ~/semantic_core/factory/scripts/interactive_api_setup.sh"
echo ""
echo "گام ۳ — در VS Code:"
echo "  F1 → Developer: Reload Window"
echo ""
echo "گام ۴ — باز کردن Continue:"
echo "  F1 → Continue: Focus on Continue View"
echo "  یا: Ctrl+B → آیکن Continue در sidebar"
echo ""
echo "═══════════════════════════════════════════════════════"
