-- ===================================================================
-- Domain Model Atomic Propositions (از سند مدل دامنه نسخه ۲.۰)
-- ===================================================================

-- منابع جدید
INSERT INTO sources (project_id, source_type, source_ref, confidence) VALUES
('semantic-core', 'domain_model', 'SEC-1-IDENTITY', 1.00),
('semantic-core', 'domain_model', 'SEC-3-ENTITY', 1.00),
('semantic-core', 'domain_model', 'SEC-3-PORT', 1.00),
('semantic-core', 'domain_model', 'SEC-3-PATH', 1.00),
('semantic-core', 'domain_model', 'SEC-3-TOPOLOGY', 1.00),
('semantic-core', 'domain_model', 'SEC-4-ROLE', 1.00),
('semantic-core', 'domain_model', 'SEC-4-CAPABILITY', 1.00),
('semantic-core', 'domain_model', 'SEC-5-STATE', 1.00),
('semantic-core', 'domain_model', 'SEC-5-CONDITION', 1.00),
('semantic-core', 'domain_model', 'SEC-6-OBSERVATION', 1.00),
('semantic-core', 'domain_model', 'SEC-8-REFERENCE', 1.00),
('semantic-core', 'domain_model', 'SEC-9-FAILURE', 1.00),
('semantic-core', 'domain_model', 'SEC-10-HYPOTHESIS', 1.00),
('semantic-core', 'domain_model', 'SEC-11-INTEGRITY', 1.00);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'D-001', 'خودروی واقعی و بازنمایی آن دو جهان جدا هستند.', 'rule', 2, 14, 2),
('semantic-core', 'D-002', 'مدل، تمام واقعیت نیست.', 'rule', 2, 14, 2),
('semantic-core', 'D-003', 'هویت خودرو با Variant و Configuration سه سطح دارد.', 'rule', 2, 14, 2),
('semantic-core', 'D-004', 'Variant شامل تیپ، موتور، گیربکس، سال و بازار است.', 'rule', 2, 14, 2),
('semantic-core', 'D-005', 'Configuration شامل ECU، نرم‌افزار و کالیبراسیون است.', 'rule', 2, 14, 2),
('semantic-core', 'D-006', 'قاعده‌ها باید به Variant مناسب متصل باشند.', 'rule', 2, 14, 2),
('semantic-core', 'D-007', 'مقدار مرجع ممکن است در Variantها متفاوت باشد.', 'rule', 2, 14, 2),
('semantic-core', 'D-008', 'سه سطح بازنمایی وجود دارد: داده، تفسیر، نتیجه.', 'rule', 2, 14, 2),
('semantic-core', 'D-009', 'در هیچ سطحی به واقعیت فیزیکی دسترسی مستقیم نداریم.', 'rule', 2, 14, 2),
('semantic-core', 'D-010', 'وضعیت موجود و مرجع باید در داده جدا باشند.', 'rule', 2, 14, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'D-011', 'Entity کوچک‌ترین واحد قابل اشاره است.', 'rule', 2, 15, 2),
('semantic-core', 'D-012', 'Entity می‌تواند فیزیکی یا منطقی باشد.', 'rule', 2, 15, 2),
('semantic-core', 'D-013', 'موجودیت مشخص با مفهوم عمومی یکی نیست.', 'rule', 2, 15, 2),
('semantic-core', 'D-014', 'Component یک موجودیت فیزیکی قابل تعویض است.', 'rule', 2, 15, 2),
('semantic-core', 'D-015', 'Module یک واحد مرکب با چند قابلیت است.', 'rule', 2, 15, 2),
('semantic-core', 'D-016', 'Aggregate گروهی از موجودیت‌ها برای یک رفتار است.', 'rule', 2, 15, 2),
('semantic-core', 'D-017', 'Pin، ترمینال فیزیکی مشخص روی قطعه است.', 'rule', 2, 16, 2),
('semantic-core', 'D-018', 'Port، نمای معنایی نقطه تعامل است.', 'rule', 2, 16, 2),
('semantic-core', 'D-019', 'Interface، قرارداد تعامل است.', 'rule', 2, 16, 2),
('semantic-core', 'D-020', 'یک پایه می‌تواند در پیکربندی‌های مختلف نقش متفاوتی داشته باشد.', 'rule', 2, 16, 2),
('semantic-core', 'D-021', 'Connection رابطه بین دو نقطه تعامل است.', 'rule', 2, 17, 2),
('semantic-core', 'D-022', 'Connection باید دامنه پیکربندی داشته باشد.', 'rule', 2, 17, 2),
('semantic-core', 'D-023', 'Connection یک رابطه است، نه یک موجودیت.', 'rule', 2, 17, 2),
('semantic-core', 'D-024', 'Path زنجیره‌ای از Connectionهاست.', 'rule', 2, 17, 2),
('semantic-core', 'D-025', 'Path از چند قطعه و مرحله می‌گذرد.', 'rule', 2, 17, 2),
('semantic-core', 'D-026', 'چهار خانواده Path در برق خودرو: توان، سیگنال، فرمان، شبکه.', 'rule', 2, 17, 2),
('semantic-core', 'D-027', 'مسیر توان یک‌طرفه و پرقدرت است.', 'rule', 2, 17, 2),
('semantic-core', 'D-028', 'مسیر سیگنال کم‌قدرت و حامل اطلاعات است.', 'rule', 2, 17, 2),
('semantic-core', 'D-029', 'مسیر فرمان از درایور تا عملگر است.', 'rule', 2, 17, 2),
('semantic-core', 'D-030', 'مسیر شبکه گره‌محور است.', 'rule', 2, 17, 2),
('semantic-core', 'D-031', 'Topology، ساختار مسیرهاست، نه یک موجودیت.', 'rule', 2, 18, 2),
('semantic-core', 'D-032', 'الگوی انتشار خرابی به Topology وابسته است.', 'rule', 2, 18, 2),
('semantic-core', 'D-033', 'خودروهای امروزی Topology ترکیبی دارند.', 'rule', 2, 18, 2),
('semantic-core', 'D-034', 'اگر مسیر بازگشت مشترک باشد، خرابی همه را تحت تأثیر قرار می‌دهد.', 'rule', 2, 18, 2),
('semantic-core', 'D-035', 'مرکز تحلیل تشخیصی، Path است.', 'rule', 2, 18, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'D-036', 'Role، نقشی است که موجودیت در بافت ایفا می‌کند.', 'rule', 2, 19, 2),
('semantic-core', 'D-037', 'Role ذاتی قطعه نیست.', 'rule', 2, 19, 2),
('semantic-core', 'D-038', 'یک سیم می‌تواند در بافت‌های مختلف نقش‌های متفاوتی داشته باشد.', 'rule', 2, 19, 2),
('semantic-core', 'D-039', 'یک ECU در بافت‌های مختلف نقش‌های متفاوتی دارد.', 'rule', 2, 19, 2),
('semantic-core', 'D-040', 'Role نباید با یک موجودیت جدید جایگزین شود.', 'rule', 2, 19, 2),
('semantic-core', 'D-041', 'RoleAssignment شامل Entity، Context و Role است.', 'rule', 2, 19, 2),
('semantic-core', 'D-042', 'نقش باید با اعتبار و شواهد ثبت شود.', 'rule', 2, 19, 2),
('semantic-core', 'D-043', 'یک موجودیت می‌تواند هم‌زمان چند نقش داشته باشد.', 'rule', 2, 19, 2),
('semantic-core', 'D-044', 'Capability، توانایی پایه‌ای است که مستقل معنا دارد.', 'rule', 2, 20, 2),
('semantic-core', 'D-045', 'Function، رفتار یا نتیجه کامل است.', 'rule', 2, 20, 2),
('semantic-core', 'D-046', 'Function از ترکیب چند Capability ساخته می‌شود.', 'rule', 2, 20, 2),
('semantic-core', 'D-047', 'Capability انتزاعی است، نه فیزیکی.', 'rule', 2, 20, 2),
('semantic-core', 'D-048', 'Capability از همکاری چند قطعه پدید می‌آید.', 'rule', 2, 20, 2),
('semantic-core', 'D-049', 'پرسش درست تشخیص، کدام Capability شکسته است می‌باشد.', 'rule', 2, 20, 2),
('semantic-core', 'D-050', 'Capability نباید با یک قطعه منفرد برابر گرفته شود.', 'rule', 2, 20, 2),
('semantic-core', 'D-051', 'Function «خنک‌کاری موتور» از چند Capability ساخته می‌شود.', 'rule', 2, 20, 2),
('semantic-core', 'D-052', 'Function پیچیده باید به Capabilityهای قابل بررسی شکسته شود.', 'rule', 2, 20, 2),
('semantic-core', 'D-053', 'موجودیت نقش را ایفا می‌کند، نه اینکه نقش را داشته باشد.', 'rule', 2, 20, 2),
('semantic-core', 'D-054', 'سه گام: Capability شکسته، سپس اجزا، سپس آزمون.', 'rule', 2, 20, 2),
('semantic-core', 'D-055', 'Capability نمی‌تواند به‌تنهایی بیانگر یک عیب باشد.', 'rule', 2, 20, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'D-056', 'State یک وضعیت گسسته و معنادار است.', 'rule', 2, 21, 2),
('semantic-core', 'D-057', 'Stateها محدود و شمارش‌پذیرند.', 'rule', 2, 21, 2),
('semantic-core', 'D-058', '«دمای موتور» یک State نیست، بلکه یک Condition است.', 'rule', 2, 21, 2),
('semantic-core', 'D-059', 'گذار بین Stateها قواعد مشخصی دارد.', 'rule', 2, 21, 2),
('semantic-core', 'D-060', 'Condition یک مقدار پیوسته یا شرط زمینه‌ای است.', 'rule', 2, 21, 2),
('semantic-core', 'D-061', 'Condition می‌تواند هر مقداری در یک بازه بگیرد.', 'rule', 2, 21, 2),
('semantic-core', 'D-062', 'State نباید با Condition یکی گرفته شود.', 'rule', 2, 21, 2),
('semantic-core', 'D-063', 'Context از ترکیب State، Condition و Variant ساخته می‌شود.', 'rule', 2, 21, 2),
('semantic-core', 'D-064', 'Context پاسخ این پرسش است: در چه بافتی معتبر است؟', 'rule', 2, 21, 2),
('semantic-core', 'D-065', 'بدون Context، هر عدد بی‌معناست.', 'rule', 2, 21, 2),
('semantic-core', 'D-066', 'Context باید ساختار قابل پرس‌وجو داشته باشد.', 'rule', 2, 21, 2),
('semantic-core', 'D-067', 'چهار سطح بافت وجود دارد: هویت، Variant، پیکربندی، لحظه.', 'rule', 2, 21, 2),
('semantic-core', 'D-068', 'تشخیص دقیق نیازمند هر چهار سطح بافت است.', 'rule', 2, 21, 2),
('semantic-core', 'D-069', 'دو تعمیرکار با یک عدد، دو تفسیر می‌توانند داشته باشند.', 'rule', 2, 21, 2),
('semantic-core', 'D-070', 'شرط را در داده باید جدا از وضعیت ثبت کرد.', 'rule', 2, 21, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'D-071', 'انرژی، سیگنال و داده سه سطح جدا هستند.', 'rule', 3, 23, 2),
('semantic-core', 'D-072', 'انرژی ممکن است وجود داشته باشد بدون اطلاعات.', 'rule', 3, 23, 2),
('semantic-core', 'D-073', 'سیگنال حامل اطلاعات یا فرمان است.', 'rule', 3, 23, 2),
('semantic-core', 'D-074', 'داده، مقدار خام ثبت‌شده است.', 'rule', 3, 23, 2),
('semantic-core', 'D-075', 'Measurement باید کمیت، واحد، نقطه، مرجع، ابزار و شرایط داشته باشد.', 'rule', 3, 23, 2),
('semantic-core', 'D-076', 'مرجع در Measurement بخشی از معناست.', 'rule', 3, 23, 2),
('semantic-core', 'D-077', 'Observation گزارش معناداری از یک Measurement در Context است.', 'rule', 3, 23, 2),
('semantic-core', 'D-078', 'Observation می‌تواند حسی یا ترکیبی باشد.', 'rule', 3, 23, 2),
('semantic-core', 'D-079', 'Observation و تفسیر باید جدا بمانند.', 'rule', 3, 23, 2),
('semantic-core', 'D-080', 'Primitiveهای سیگنال، واژگان پایه توصیف هستند.', 'rule', 3, 23, 2),
('semantic-core', 'D-081', 'یک Observation می‌تواند چند Primitive داشته باشد.', 'rule', 3, 23, 2),
('semantic-core', 'D-082', 'Reference توصیف انتظار است، نه واقعیت.', 'rule', 3, 22, 2),
('semantic-core', 'D-083', 'هر Reference باید دامنه و منشأ داشته باشد.', 'rule', 3, 22, 2),
('semantic-core', 'D-084', 'Reference می‌تواند مشخصه فنی، رفتاری یا میدانی باشد.', 'rule', 3, 22, 2),
('semantic-core', 'D-085', 'ارتقای Observation به Reference نیازمند شواهد است.', 'rule', 3, 22, 2),
('semantic-core', 'D-086', 'Failure Mode با Fault و Symptom متفاوت است.', 'rule', 3, 24, 2),
('semantic-core', 'D-087', 'Failure Mode الگوی از کار افتادن است.', 'rule', 3, 24, 2),
('semantic-core', 'D-088', 'Symptom نشانه از دید کاربر است.', 'rule', 3, 24, 2),
('semantic-core', 'D-089', 'Complaint زبان مشتری است، نه علت.', 'rule', 3, 24, 2),
('semantic-core', 'D-090', 'شکایت باید به نشانه‌های مشخص تفکیک شود.', 'rule', 3, 24, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'D-091', 'Hypothesis یک گزاره قابل بررسی است.', 'rule', 3, 25, 2),
('semantic-core', 'D-092', 'Hypothesis نباید فقط نام یک قطعه باشد.', 'rule', 3, 25, 2),
('semantic-core', 'D-093', 'Hypothesis می‌تواند در چند سطح مطرح شود.', 'rule', 3, 25, 2),
('semantic-core', 'D-094', 'Test باید هدف تفکیک داشته باشد.', 'rule', 3, 25, 2),
('semantic-core', 'D-095', 'Test شامل Target، Precondition، Method، Outcomes است.', 'rule', 3, 25, 2),
('semantic-core', 'D-096', 'Evidence به‌عنوان یک رابطه به Hypothesis متصل می‌شود.', 'rule', 3, 25, 2),
('semantic-core', 'D-097', 'Evidence می‌تواند Support، Weaken، Neutral یا Conflict باشد.', 'rule', 3, 25, 2),
('semantic-core', 'D-098', 'Evidence باید Method و Context داشته باشد.', 'rule', 3, 25, 2),
('semantic-core', 'D-099', 'استقلال شواهد مهم است.', 'rule', 3, 25, 2),
('semantic-core', 'D-100', 'شواهد همبسته، یک شاهد محسوب می‌شوند.', 'rule', 3, 25, 2),
('semantic-core', 'D-101', 'Diagnostic Episode یک روایت است، نه یک موجودیت.', 'rule', 3, 25, 2),
('semantic-core', 'D-102', 'Episode از لحظه مسئله تا بسته شدن است.', 'rule', 3, 25, 2),
('semantic-core', 'D-103', 'Episode باید متمرکز باشد.', 'rule', 3, 25, 2),
('semantic-core', 'D-104', 'هر Observation باید Context و زمان داشته باشد.', 'rule', 3, 26, 2),
('semantic-core', 'D-105', 'هر انتساب نقش باید بافت داشته باشد.', 'rule', 3, 26, 2);
