-- ===================================================================
-- Knowledge Governance Atomic Propositions
-- ===================================================================

-- منابع جدید
INSERT INTO sources (project_id, source_type, source_ref, confidence) VALUES
('semantic-core', 'knowledge_governance', 'SEC-1-MISSION', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-3-CLAIM', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-4-TYPES', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-5-SOURCE', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-6-SCOPE', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-7-REFERENCE', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-8-EVIDENCE', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-9-STATUS', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-10-CONFIDENCE', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-11-PIPELINE', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-13-CONFLICT', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-14-VERSION', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-16-CASE', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-18-NEGATIVE', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-20-AI', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-21-AUDIT', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-23-SAFETY', 1.00),
('semantic-core', 'knowledge_governance', 'SEC-24-CONTRACT', 1.00);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'G-001', 'واحد اصلی حاکمیت دانش، Claim (ادعا) است.', 'rule', 3, 31, 2),
('semantic-core', 'G-002', 'یک سند می‌تواند ده‌ها Claim داشته باشد.', 'rule', 3, 31, 2),
('semantic-core', 'G-003', 'یک Claim باید قابل ارزیابی مستقل باشد.', 'rule', 3, 31, 2),
('semantic-core', 'G-004', 'هر Claim شامل proposition، type، scope، source، evidence و status است.', 'rule', 3, 32, 2),
('semantic-core', 'G-005', 'Claim مبهم به دانش فعال تبدیل نمی‌شود.', 'rule', 3, 32, 2),
('semantic-core', 'G-006', '«P0335 یعنی سنسور خراب است» یک Claim قابل ارزیابی نیست.', 'rule', 3, 32, 2),
('semantic-core', 'G-007', 'جمله توصیفی وقتی Claim می‌شود که قابل رد یا تأیید باشد.', 'rule', 3, 32, 2),
('semantic-core', 'G-008', 'Observation یک Claim نیست.', 'rule', 3, 32, 2),
('semantic-core', 'G-009', 'Measurement یک Claim نیست.', 'rule', 3, 32, 2),
('semantic-core', 'G-010', 'تجزیه سند به Claim، ارزیابی دقیق‌تر را ممکن می‌کند.', 'rule', 3, 32, 2),
('semantic-core', 'G-011', 'هفت نوع دانش وجود دارد.', 'rule', 3, 33, 2),
('semantic-core', 'G-012', 'Observation-derived دانش از مشاهده است.', 'rule', 3, 33, 2),
('semantic-core', 'G-013', 'Reference، انتظار مستند یا پذیرفته‌شده است.', 'rule', 3, 33, 2),
('semantic-core', 'G-014', 'Empirical Pattern، الگوی تکرارشونده است.', 'rule', 3, 33, 2),
('semantic-core', 'G-015', 'Diagnostic Rule، رابطه شرطی برای هدایت تشخیص است.', 'rule', 3, 33, 2),
('semantic-core', 'G-016', 'Test Knowledge، دانش درباره قدرت تفکیک آزمون است.', 'rule', 3, 33, 2),
('semantic-core', 'G-017', 'Negative Knowledge، دانش درباره محدودیت است.', 'rule', 3, 33, 2),
('semantic-core', 'G-018', 'Exception، شرط محدودکننده یک دانش است.', 'rule', 3, 33, 2),
('semantic-core', 'G-019', 'نوع دانش باید در لحظه ثبت Claim مشخص شود.', 'rule', 3, 33, 2),
('semantic-core', 'G-020', 'بدون نوع دانش، ارزیابی سطح اعتماد ممکن نیست.', 'rule', 3, 33, 2),
('semantic-core', 'G-021', 'Reference و Empirical Pattern، دو نوع متفاوت دانش هستند.', 'rule', 3, 33, 2),
('semantic-core', 'G-022', 'Exception یک نوع مستقل است، نه زیرمجموعه Reference.', 'rule', 3, 33, 2),
('semantic-core', 'G-023', 'سه نوع Exception رایج: تعمیر، پیکربندی، شرایط محیطی.', 'rule', 3, 33, 2),
('semantic-core', 'G-024', 'Negative Knowledge جلوی خطاهای رایج را می‌گیرد.', 'rule', 3, 33, 2),
('semantic-core', 'G-025', 'نوع دانش یکسان برای همه Claimها، ارزیابی نادرست ایجاد می‌کند.', 'rule', 3, 33, 2),
('semantic-core', 'G-026', 'Claim باید از یک منبع قابل شناسایی آمده باشد.', 'rule', 3, 34, 2),
('semantic-core', 'G-027', 'Source، منبع است؛ Claim، گزاره استخراج‌شده است.', 'rule', 3, 34, 2),
('semantic-core', 'G-028', 'یک Source می‌تواند ده‌ها Claim داشته باشد.', 'rule', 3, 34, 2),
('semantic-core', 'G-029', 'Source با Claim نباید یکی گرفته شود.', 'rule', 3, 34, 2),
('semantic-core', 'G-030', 'هر Claim باید یک Evidence Relation با شواهد داشته باشد.', 'rule', 3, 34, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'G-031', 'Scope بخشی از معنای دانش است.', 'rule', 3, 35, 2),
('semantic-core', 'G-032', 'Claim بدون Scope، یک Claim مبهم است.', 'rule', 3, 35, 2),
('semantic-core', 'G-033', 'Scope شامل هویت، Variant، Configuration، State و Condition است.', 'rule', 3, 35, 2),
('semantic-core', 'G-034', 'تعمیم از یک Variant به چند Variant، یک تغییر دانشی است.', 'rule', 3, 35, 2),
('semantic-core', 'G-035', 'Scope نباید در متن آزاد پنهان شود.', 'rule', 3, 35, 2),
('semantic-core', 'G-036', 'Scope باید ساختار قابل پرس‌وجو داشته باشد.', 'rule', 3, 35, 2),
('semantic-core', 'G-037', 'وضعیت Scope می‌تواند کامل، ناقص، نامعلوم یا متعارض باشد.', 'rule', 3, 35, 2),
('semantic-core', 'G-038', 'هر Claim باید Scope خود را حمل کند.', 'rule', 3, 35, 2),
('semantic-core', 'G-039', 'فیلتر Scope در تصمیم‌گیری ضروری است.', 'rule', 3, 35, 2),
('semantic-core', 'G-040', 'Scope نامنطبق، دانش را غیرقابل اعمال می‌کند.', 'rule', 3, 35, 2),
('semantic-core', 'G-041', 'تفکیک Reference از As-Found بنیادین است.', 'rule', 3, 36, 2),
('semantic-core', 'G-042', 'Reference، انتظار است؛ As-Found، واقعیت مشاهده‌شده.', 'rule', 3, 36, 2),
('semantic-core', 'G-043', 'Difference یک واقعیت است، نه یک علت.', 'rule', 3, 36, 2),
('semantic-core', 'G-044', 'ارتقای Observation به Reference نیازمند سه شرط است.', 'rule', 3, 36, 2),
('semantic-core', 'G-045', 'Reference در طول زمان می‌تواند تغییر کند.', 'rule', 3, 36, 2),
('semantic-core', 'G-046', 'Reference قبلی به Superseded منتقل می‌شود، نه حذف.', 'rule', 3, 36, 2),
('semantic-core', 'G-047', 'شش بُعد کیفیت Evidence وجود دارد.', 'rule', 3, 37, 2),
('semantic-core', 'G-048', 'Measurement Quality، Context Completeness، Reproducibility از ابعاد هستند.', 'rule', 3, 37, 2),
('semantic-core', 'G-049', 'Independence، Claim Fit و Counter Evidence سه بُعد دیگرند.', 'rule', 3, 37, 2),
('semantic-core', 'G-050', 'همه ابعاد نباید در یک Trust Score پنهان شوند.', 'rule', 3, 37, 2),
('semantic-core', 'G-051', 'شواهد همبسته، یک شاهد محسوب می‌شوند.', 'rule', 3, 37, 2),
('semantic-core', 'G-052', 'شواهد مستقل از منابع مختلف ارزشمندترند.', 'rule', 3, 37, 2),
('semantic-core', 'G-053', 'Claim Fit ارزیابی می‌کند که شاهد دقیقاً همان ادعا را پشتیبانی می‌کند.', 'rule', 3, 37, 2),
('semantic-core', 'G-054', 'Counter Evidence باید ثبت شود.', 'rule', 3, 37, 2),
('semantic-core', 'G-055', 'حذف شواهد مخالف ممنوع است.', 'rule', 3, 37, 2),
('semantic-core', 'G-056', 'Provenance، داستان زندگی یک Claim است.', 'rule', 3, 34, 2),
('semantic-core', 'G-057', 'Provenance شامل ورود، تغییر و ارتقا است.', 'rule', 3, 34, 2),
('semantic-core', 'G-058', 'Provenance در بازبینی ضروری است.', 'rule', 3, 34, 2),
('semantic-core', 'G-059', 'Evidence می‌تواند Supporting، Counter یا Neutral باشد.', 'rule', 3, 34, 2),
('semantic-core', 'G-060', 'کیفیت Evidence باید در نسبت با Claim ارزیابی شود.', 'rule', 3, 34, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'G-061', 'هفت وضعیت دانش وجود دارد.', 'rule', 3, 38, 2),
('semantic-core', 'G-062', 'وضعیت Draft، در حال تدوین است.', 'rule', 3, 38, 2),
('semantic-core', 'G-063', 'وضعیت Under Review، در حال ارزیابی است.', 'rule', 3, 38, 2),
('semantic-core', 'G-064', 'وضعیت Active، پذیرفته‌شده برای Scope مشخص است.', 'rule', 3, 38, 2),
('semantic-core', 'G-065', 'وضعیت Disputed، اختلاف مستند دارد.', 'rule', 3, 38, 2),
('semantic-core', 'G-066', 'وضعیت Superseded، نسخه جدید جایگزین شده است.', 'rule', 3, 38, 2),
('semantic-core', 'G-067', 'وضعیت Deprecated، مصرف آن توصیه نمی‌شود.', 'rule', 3, 38, 2),
('semantic-core', 'G-068', 'وضعیت Rejected، پذیرفته نشده است.', 'rule', 3, 38, 2),
('semantic-core', 'G-069', 'وضعیت دانش با وضعیت فرضیه متفاوت است.', 'rule', 3, 38, 2),
('semantic-core', 'G-070', 'مسیرهای گذر بین وضعیت‌ها باید در Provenance ثبت شوند.', 'rule', 3, 38, 2),
('semantic-core', 'G-071', 'Confidence باید توضیح‌پذیر باشد.', 'rule', 3, 39, 2),
('semantic-core', 'G-072', 'Confidence از هفت عامل ساخته می‌شود.', 'rule', 3, 39, 2),
('semantic-core', 'G-073', 'کیفیت Source، Evidence، Scope Fit و Reproducibility از عوامل هستند.', 'rule', 3, 39, 2),
('semantic-core', 'G-074', 'Independence، Counter Evidence و Review از عوامل دیگرند.', 'rule', 3, 39, 2),
('semantic-core', 'G-075', 'یک عدد واحد Confidence کافی نیست.', 'rule', 3, 39, 2),
('semantic-core', 'G-076', 'Confidence در انتخاب آزمون بعدی وارد می‌شود.', 'rule', 3, 39, 2),
('semantic-core', 'G-077', 'Confidence مختلط می‌تواند در بعضی ابعاد قوی و بعضی ضعیف باشد.', 'rule', 3, 39, 2),
('semantic-core', 'G-078', 'Pipeline پذیرش شامل Capture، Classify، Scope، Provenance و Evidence است.', 'rule', 3, 40, 2),
('semantic-core', 'G-079', 'پس از Review، سه حالت Reject، Hold، Activate ممکن است.', 'rule', 3, 40, 2),
('semantic-core', 'G-080', 'Monitor و Challenge پس از فعال شدن لازم است.', 'rule', 3, 40, 2),
('semantic-core', 'G-081', 'پایپلاین بدون Review کامل نمی‌شود.', 'rule', 3, 40, 2),
('semantic-core', 'G-082', 'پنج نقش کلیدی در حاکمیت دانش وجود دارد.', 'rule', 3, 40, 2),
('semantic-core', 'G-083', 'Knowledge Steward، سلامت چرخه را تضمین می‌کند.', 'rule', 3, 40, 2),
('semantic-core', 'G-084', 'Domain Reviewer، صحت معنای فنی را بررسی می‌کند.', 'rule', 3, 40, 2),
('semantic-core', 'G-085', 'Evidence Reviewer، کیفیت شواهد را بررسی می‌کند.', 'rule', 3, 40, 2),
('semantic-core', 'G-086', 'Scope Reviewer، شرایط اعتبار را بررسی می‌کند.', 'rule', 3, 40, 2),
('semantic-core', 'G-087', 'Safety/Legal Reviewer، موارد ایمنی یا حقوقی را بررسی می‌کند.', 'rule', 3, 40, 2),
('semantic-core', 'G-088', 'تعارض بین نقش‌ها به تصمیم محافظه‌کارانه منجر می‌شود.', 'rule', 3, 40, 2),
('semantic-core', 'G-089', 'نقش‌ها در پروژه کوچک می‌توانند ترکیب شوند.', 'rule', 3, 40, 2),
('semantic-core', 'G-090', 'نقش‌ها نباید نامرئی بمانند.', 'rule', 3, 40, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'G-091', 'تعارض نباید پنهان شود.', 'rule', 3, 41, 2),
('semantic-core', 'G-092', 'حل تعارض در پنج گام انجام می‌شود.', 'rule', 3, 41, 2),
('semantic-core', 'G-093', 'گام اول: بررسی معنایی.', 'rule', 3, 41, 2),
('semantic-core', 'G-094', 'گام دوم: بررسی Scope، Context، زمان.', 'rule', 3, 41, 2),
('semantic-core', 'G-095', 'گام سوم: بررسی منبع و شواهد.', 'rule', 3, 41, 2),
('semantic-core', 'G-096', 'گام چهارم: تصمیم در مورد رابطه.', 'rule', 3, 41, 2),
('semantic-core', 'G-097', 'گام پنجم: ثبت تصمیم و دلیل.', 'rule', 3, 41, 2),
('semantic-core', 'G-098', 'حل تعارض با رأی اکثریت ممنوع است.', 'forbidden', 3, 41, 2),
('semantic-core', 'G-099', 'انواع تعارض: دامنه، زمانی، منبع، تفسیری، کل‌نگر.', 'rule', 3, 41, 2),
('semantic-core', 'G-100', 'شش نوع رویداد نسخه‌بندی وجود دارد.', 'rule', 3, 42, 2),
('semantic-core', 'G-101', 'رویدادها: Create، Review، Revise، Supersede، Narrow/Expand، Retire.', 'rule', 3, 42, 2),
('semantic-core', 'G-102', 'هر تغییر نیازمند پاسخ به پنج پرسش است.', 'rule', 3, 42, 2),
('semantic-core', 'G-103', 'نسخه قبلی هرگز حذف نمی‌شود.', 'rule', 3, 42, 2),
('semantic-core', 'G-104', 'Lineage، تبار یک Claim را ثبت می‌کند.', 'rule', 3, 42, 2),
('semantic-core', 'G-105', 'سه نوع وابستگی در Lineage وجود دارد.', 'rule', 3, 42, 2),
('semantic-core', 'G-106', 'Case به Knowledge تبدیل می‌شود، اما نه خودکار.', 'rule', 3, 43, 2),
('semantic-core', 'G-107', 'چرخه تبدیل شامل شش گام است.', 'rule', 3, 43, 2),
('semantic-core', 'G-108', 'خروجی Review می‌تواند شش حالت داشته باشد.', 'rule', 3, 43, 2),
('semantic-core', 'G-109', 'Negative Knowledge بخشی از حافظه دانش است.', 'rule', 3, 44, 2),
('semantic-core', 'G-110', 'دانش منفی نباید حذف شود.', 'rule', 3, 44, 2),
('semantic-core', 'G-111', 'AI پیشنهاددهنده است، نه صاحب اختیار حقیقت.', 'rule', 3, 45, 2),
('semantic-core', 'G-112', 'سه سطح استفاده از AI وجود دارد.', 'rule', 3, 45, 2),
('semantic-core', 'G-113', 'در همه سطوح، Review انسانی ضروری است.', 'rule', 3, 45, 2),
('semantic-core', 'G-114', 'AI نمی‌تواند مستقیم به دانش فعال تبدیل شود.', 'rule', 3, 45, 2),
('semantic-core', 'G-115', 'Audit Trace مسیر تصمیم را بازسازی می‌کند.', 'rule', 3, 46, 2),
('semantic-core', 'G-116', 'دو مسیر حسابرسی وجود دارد.', 'rule', 3, 46, 2),
('semantic-core', 'G-117', 'سه سطح Audit: فوری، میان‌مدت، بلندمدت.', 'rule', 3, 46, 2),
('semantic-core', 'G-118', 'ترتیب: اول ایمنی، سپس ارزش اطلاعات.', 'rule', 3, 47, 2),
('semantic-core', 'G-119', 'سه سطح ریسک: کم‌خطر، متوسط، پرخطر.', 'rule', 3, 47, 2),
('semantic-core', 'G-120', 'قرارداد حداقلی دانش دوازده عنصر دارد.', 'rule', 3, 48, 2);
