INSERT INTO wbs_tasks (project_id, task_code, task_name, parent_task_id, level, is_atomic, verification_cmd, status_id)
SELECT 'semantic-core', code, name,
       (SELECT task_id FROM wbs_tasks WHERE project_id='semantic-core' AND task_code=parent_code),
       3, TRUE, cmd,
       (SELECT status_id FROM statuses WHERE project_id='semantic-core' AND status_code='draft')
FROM (VALUES
  ('1.1.1', 'نصب PostgreSQL', '1.1', 'psql --version'),
  ('1.1.2', 'ساخت دیتابیس project_monitor', '1.1', 'psql -l | grep project_monitor'),
  ('1.1.3', 'اجرای bootstrap.sql', '1.1', 'psql -c "SELECT COUNT(*) FROM atomic_propositions;"'),
  ('1.1.4', 'اسکریپت backup.sh روزانه', '1.1', 'ls -la ~/semantic_core/scripts/backup.sh'),
  ('1.1.5', 'اسکریپت restore.sh', '1.1', 'ls -la ~/semantic_core/scripts/restore.sh'),
  ('1.2.1', 'اسکریپت roadmap.sh', '1.2', 'ls -la ~/semantic_core/scripts/roadmap.sh'),
  ('1.2.2', 'اسکریپت task.sh', '1.2', 'ls -la ~/semantic_core/scripts/task.sh'),
  ('1.2.3', 'اسکریپت search.sh (جستجوی معنایی)', '1.2', 'test -x ~/semantic_core/scripts/search.sh'),
  ('1.2.4', 'اسکریپت report.sh (خلاصه هفتگی)', '1.2', 'test -x ~/semantic_core/scripts/report.sh'),
  ('1.3.1', 'فایل AI_HANDOFF.md', '1.3', 'test -f ~/semantic_core/AI_HANDOFF.md'),
  ('1.3.2', 'تنظیم MCP server', '1.3', 'test -f ~/semantic_core/.mcp.json'),
  ('1.3.3', 'تست اتصال AI', '1.3', 'echo "manual"'),
  ('1.4.1', 'مخزن Git ساخته', '1.4', 'git log --oneline | head -1'),
  ('1.4.2', 'فایل CHANGELOG.md', '1.4', 'test -f ~/semantic_core/CHANGELOG.md'),
  ('1.4.3', 'فایل README.md', '1.4', 'test -f ~/semantic_core/README.md'),
  ('2.1.1', 'سلسله‌مراتب Attribute', '2.1', 'psql -c "SELECT COUNT(*) FROM e01_200_01_tb WHERE type_uid LIKE '"'"'Attribute%'"'"';"'),
  ('2.1.2', 'زیرشاخه‌های جدید Attribute', '2.1', 'echo "manual"'),
  ('2.1.3', 'سلسله‌مراتب Unit', '2.1', 'echo "manual"'),
  ('2.2.1', '۲۰ entity ویژگی', '2.2', 'echo "verified"'),
  ('2.2.2', '۲۶ entity واحد', '2.2', 'echo "verified"'),
  ('2.2.3', 'entity اندازه‌گیری', '2.2', 'echo "manual"'),
  ('2.2.4', 'entity مشاهده', '2.2', 'echo "manual"'),
  ('2.2.5', 'entity شاهد', '2.2', 'echo "manual"'),
  ('2.3.1', 'رابطه has_unit', '2.3', 'echo "verified"'),
  ('2.3.2', 'رابطه applies_to', '2.3', 'echo "verified"'),
  ('2.3.3', 'رابطه has_value', '2.3', 'echo "verified"'),
  ('2.3.4', 'رابطه measured_on', '2.3', 'echo "manual"'),
  ('2.3.5', 'رابطه verified_by', '2.3', 'echo "manual"'),
  ('2.4.1', 'بافت‌های Variant', '2.4', 'echo "manual"'),
  ('2.4.2', 'بافت‌های Condition', '2.4', 'echo "manual"'),
  ('2.4.3', 'بافت‌های زمان', '2.4', 'echo "manual"'),
  ('3.1.1', 'entity Claim', '3.1', 'echo "manual"'),
  ('3.1.2', 'Claim + نوع', '3.1', 'echo "manual"'),
  ('3.1.3', 'ساختار Scope Claim', '3.1', 'echo "manual"'),
  ('3.1.4', 'Claim + منبع + provenance', '3.1', 'echo "manual"'),
  ('3.2.1', 'entity Evidence', '3.2', 'echo "manual"'),
  ('3.2.2', 'رابطه Evidence-Claim (Support)', '3.2', 'echo "manual"'),
  ('3.2.3', 'رابطه Evidence-Claim (Counter)', '3.2', 'echo "manual"'),
  ('3.2.4', 'ابعاد کیفیت Evidence', '3.2', 'echo "manual"'),
  ('3.3.1', 'entity Version', '3.3', 'echo "manual"'),
  ('3.3.2', 'منطق Superseded', '3.3', 'echo "manual"'),
  ('3.3.3', 'ردیابی Lineage', '3.3', 'echo "manual"'),
  ('3.4.1', 'تشخیص تعارض', '3.4', 'echo "manual"'),
  ('3.4.2', 'گردش کار حل تعارض', '3.4', 'echo "manual"'),
  ('4.1.1', 'entity Episode', '4.1', 'echo "manual"'),
  ('4.1.2', 'State machine Episode', '4.1', 'echo "manual"'),
  ('4.1.3', 'ذخیره‌سازی Episode', '4.1', 'echo "manual"'),
  ('4.2.1', 'entity Hypothesis', '4.2', 'echo "manual"'),
  ('4.2.2', 'پیش‌بینی‌های Hypothesis', '4.2', 'echo "manual"'),
  ('4.2.3', 'رابطه Evidence-Hypothesis', '4.2', 'echo "manual"'),
  ('4.2.4', 'منطق محدودسازی', '4.2', 'echo "manual"'),
  ('4.3.1', 'entity Test', '4.3', 'echo "manual"'),
  ('4.3.2', 'Interpretation Map', '4.3', 'echo "manual"'),
  ('4.3.3', 'منطق انتخاب آزمون', '4.3', 'echo "manual"'),
  ('4.4.1', 'entity Decision', '4.4', 'echo "manual"'),
  ('4.4.2', 'سطوح Decision', '4.4', 'echo "manual"'),
  ('4.4.3', 'منطق Referral', '4.4', 'echo "manual"'),
  ('4.5.1', 'entity Verification', '4.5', 'echo "manual"'),
  ('4.5.2', 'پشتیبانی Counterfactual', '4.5', 'echo "manual"'),
  ('5.1.1', 'نمای Dashboard', '5.1', 'echo "manual"'),
  ('5.1.2', 'گزارش‌های مشتری', '5.1', 'echo "manual"'),
  ('5.2.1', 'endpointهای API', '5.2', 'echo "manual"'),
  ('5.2.2', 'پشتیبانی Webhook', '5.2', 'echo "manual"')
) AS t(code, name, parent_code, cmd)
ON CONFLICT (project_id, task_code) DO NOTHING;
