-- ===================================================================
-- Constitution Atomic Propositions (از قانون اساسی نسخه ۵.۰)
-- ===================================================================

-- افزودن منابع
INSERT INTO sources (project_id, source_type, source_ref, confidence) VALUES
('semantic-core', 'constitution', 'PRINCIPLE-06', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-07', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-08', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-09', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-10', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-11', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-12', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-13', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-14', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-15', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-16', 1.00),
('semantic-core', 'constitution', 'PRINCIPLE-17', 1.00);

-- دامنه‌های جدید
INSERT INTO scopes (project_id, scope_code, description) VALUES
('semantic-core', 'SCOPE-DIAGNOSTIC', 'لایه تشخیص'),
('semantic-core', 'SCOPE-BUSINESS', 'لایه کسب‌وکار'),
('semantic-core', 'SCOPE-GOVERNANCE', 'لایه حاکمیت');

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'C-001', 'هدف پروژه، تبدیل دانش برق خودرو به دانش قابل انتساب است.', 'goal', 1, 1, 2),
('semantic-core', 'C-002', 'هدف پروژه، تبدیل دانش برق خودرو به دانش قابل توضیح است.', 'goal', 1, 1, 2),
('semantic-core', 'C-003', 'هدف پروژه، تبدیل دانش برق خودرو به دانش قابل آزمون است.', 'goal', 1, 1, 2),
('semantic-core', 'C-004', 'هدف پروژه، تبدیل دانش برق خودرو به دانش قابل ردیابی است.', 'goal', 1, 1, 2),
('semantic-core', 'C-005', 'هدف پروژه، تبدیل دانش برق خودرو به دانش قابل انتقال است.', 'goal', 1, 1, 2),
('semantic-core', 'C-006', 'واحد ارزش، توانایی کاهش فضای خطا است.', 'rule', 1, 1, 2),
('semantic-core', 'C-007', 'محتوا به‌تنهایی معیار موفقیت نیست.', 'rule', 1, 1, 2),
('semantic-core', 'C-008', 'پرش از نشانه به تعمیر ممنوع است.', 'rule', 1, 1, 2),
('semantic-core', 'C-009', 'الگوریتم یک بازنمایی از واقعیت است، نه خودِ واقعیت.', 'rule', 1, 2, 2),
('semantic-core', 'C-010', 'هیچ بازنمایی بدون منشأ، خودِ واقعیت نیست.', 'rule', 1, 2, 2),
('semantic-core', 'C-011', 'وضعیت موجود باید از مرجع جدا باشد.', 'rule', 1, 2, 2),
('semantic-core', 'C-012', 'اختلاف یک واقعیت است، نه یک علت.', 'rule', 1, 2, 2),
('semantic-core', 'C-013', 'نمی‌دانیم یک حالت معتبر است.', 'rule', 1, 2, 2),
('semantic-core', 'C-014', 'شاهد منفرد کافی نیست.', 'rule', 1, 2, 2),
('semantic-core', 'C-015', 'DTC یک بازنمایی است، نه واقعیت.', 'rule', 1, 2, 2),
('semantic-core', 'C-016', 'موجودیت، چیزی است که قابل اشاره است.', 'rule', 2, 3, 2),
('semantic-core', 'C-017', 'نقش، ذاتی موجودیت نیست.', 'rule', 2, 3, 2),
('semantic-core', 'C-018', 'نقش، به بافت وابسته است.', 'rule', 2, 3, 2),
('semantic-core', 'C-019', 'سیگنال، الگوی فیزیکی حامل اطلاعات است.', 'rule', 2, 3, 2),
('semantic-core', 'C-020', 'قابلیت، از همکاری چند موجودیت پدید می‌آید.', 'rule', 2, 3, 2),
('semantic-core', 'C-021', 'قابلیت، ذاتاً یک قطعه نیست.', 'rule', 2, 3, 2),
('semantic-core', 'C-022', 'State یک وضعیت گسسته است.', 'rule', 2, 4, 2),
('semantic-core', 'C-023', 'Condition یک مقدار پیوسته است.', 'rule', 2, 4, 2),
('semantic-core', 'C-024', 'Context از ترکیب State و Condition ساخته می‌شود.', 'rule', 2, 4, 2),
('semantic-core', 'C-025', 'هر قاعده باید به یک Variant متصل باشد.', 'rule', 2, 4, 2),
('semantic-core', 'C-026', 'تعمیم از یک Variant به همه ممنوع است.', 'rule', 2, 4, 2),
('semantic-core', 'C-027', 'چهار خانواده مسیر در برق خودرو وجود دارد.', 'rule', 2, 1, 2),
('semantic-core', 'C-028', 'مسیر توان از منبع تا بازگشت است.', 'rule', 2, 1, 2),
('semantic-core', 'C-029', 'مسیر سیگنال از سنسور تا ECU است.', 'rule', 2, 1, 2),
('semantic-core', 'C-030', 'مسیر خروجی ECU از درایور تا عملگر است.', 'rule', 2, 1, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'C-031', 'مسیر شبکه، گره‌محور است.', 'rule', 2, 1, 2),
('semantic-core', 'C-032', 'پرسش درست در تشخیص، کدام Capability شکسته است می‌باشد.', 'rule', 3, 6, 2),
('semantic-core', 'C-033', 'وجود ولتاژ در یک نقطه، سلامت مسیر را اثبات نمی‌کند.', 'rule', 3, 6, 2),
('semantic-core', 'C-034', 'اندازه‌گیری ولتاژ در مدار پرقدرت باید زیر بار انجام شود.', 'rule', 3, 6, 2),
('semantic-core', 'C-035', 'مسیر بازگشت باید در اندازه‌گیری لحاظ شود.', 'rule', 3, 6, 2),
('semantic-core', 'C-036', 'سیگنال، اندازه‌گیری و مشاهده سه سطح جدا هستند.', 'rule', 3, 7, 2),
('semantic-core', 'C-037', 'هر مشاهده باید Context داشته باشد.', 'rule', 3, 7, 2),
('semantic-core', 'C-038', 'هر اندازه‌گیری باید شش جزء داشته باشد: کمیت، واحد، نقطه، مرجع، ابزار، شرایط.', 'rule', 3, 7, 2),
('semantic-core', 'C-039', 'DTC یک مشاهده است، نه علت.', 'rule', 3, 7, 2),
('semantic-core', 'C-040', 'مشاهده و تفسیر باید جدا باشند.', 'rule', 3, 7, 2),
('semantic-core', 'C-041', 'هر ادعا باید منبع داشته باشد.', 'rule', 1, 8, 2),
('semantic-core', 'C-042', 'هر ادعا باید Provenance داشته باشد.', 'rule', 1, 8, 2),
('semantic-core', 'C-043', 'هر ادعا باید دامنه اعتبار داشته باشد.', 'rule', 1, 8, 2),
('semantic-core', 'C-044', 'هر ادعا باید نسخه و زمان داشته باشد.', 'rule', 1, 8, 2),
('semantic-core', 'C-045', 'هر ادعا باید سطح اطمینان داشته باشد.', 'rule', 1, 8, 2),
('semantic-core', 'C-046', 'هر ادعا باید شواهد پشتیبان داشته باشد.', 'rule', 1, 8, 2),
('semantic-core', 'C-047', 'تشخیص، تفکیک فرضیه‌هاست، نه حدس‌زدن قطعه.', 'rule', 3, 9, 2),
('semantic-core', 'C-048', 'رد کردن فرضیه از اثبات آن ارزان‌تر است.', 'rule', 3, 9, 2),
('semantic-core', 'C-049', 'تعویض قطعه به‌عنوان آزمون ممنوع است.', 'rule', 3, 9, 2),
('semantic-core', 'C-050', 'آزمون باید قدرت تفکیک داشته باشد.', 'rule', 3, 10, 2),
('semantic-core', 'C-051', 'آزمون باید کم‌هزینه و کم‌ریسک باشد.', 'rule', 3, 10, 2),
('semantic-core', 'C-052', 'آزمون باید برگشت‌پذیر باشد.', 'rule', 3, 10, 2),
('semantic-core', 'C-053', 'آزمون بدون هدف، اتلاف منابع است.', 'rule', 3, 10, 2),
('semantic-core', 'C-054', 'تشخیص، تعمیر و راستی‌آزمایی سه مرحله جدا هستند.', 'rule', 3, 11, 2),
('semantic-core', 'C-055', 'تعمیر جایگزین راستی‌آزمایی نیست.', 'rule', 3, 11, 2),
('semantic-core', 'C-056', 'راستی‌آزمایی باید مستقل از تعمیر باشد.', 'rule', 3, 11, 2),
('semantic-core', 'C-057', 'منطق دامنه نباید به UI وابسته باشد.', 'rule', 1, 12, 2),
('semantic-core', 'C-058', 'داده، قاعده، مشاهده و تصمیم باید جدا باشند.', 'rule', 1, 12, 2),
('semantic-core', 'C-059', 'هر تصمیم مهم باید مسیر حسابرسی داشته باشد.', 'rule', 1, 12, 2),
('semantic-core', 'C-060', 'AI نباید بدون قرارداد، حقیقت جدید بسازد.', 'rule', 1, 12, 2);

INSERT INTO atomic_propositions (project_id, prop_code, proposition, prop_type, scope_id, source_id, status_id) VALUES
('semantic-core', 'C-061', 'قانون اساسی نباید هر بار که یک قاعده غلط کشف شد تغییر کند.', 'rule', 1, 13, 2),
('semantic-core', 'C-062', 'تجربه میدان باید بتواند قاعده دامنه را اصلاح کند.', 'rule', 1, 13, 2),
('semantic-core', 'C-063', 'هر تغییر دانش باید مشخص کند چه چیزی تغییر کرد.', 'rule', 1, 13, 2),
('semantic-core', 'C-064', 'هر تصمیم پرخطر باید مرز توقف داشته باشد.', 'rule', 1, 14, 2),
('semantic-core', 'C-065', 'عدم قطعیت باید در خروجی دیده شود.', 'rule', 1, 14, 2),
('semantic-core', 'C-066', 'در موارد پرریسک، سیستم تصمیم‌یار است، نه تصمیم‌ساز.', 'rule', 1, 14, 2),
('semantic-core', 'C-067', 'گسترش باید از منطق مشترک بیاید، نه کپی داده.', 'rule', 1, 15, 2),
('semantic-core', 'C-068', 'هر حوزه جدید باید ابتدا انتقال مدل پایه را اثبات کند.', 'rule', 1, 15, 2),
('semantic-core', 'C-069', 'اعداد فازبندی، قانون اساسی نیستند.', 'rule', 1, 15, 2),
('semantic-core', 'C-070', 'ارزش اقتصادی تابع ارزش تشخیصی است.', 'rule', 5, 16, 2),
('semantic-core', 'C-071', 'منشأ هر داده باید از نظر حقوقی روشن باشد.', 'rule', 5, 16, 2),
('semantic-core', 'C-072', 'ادعاهای عملکردی باید قابل سنجش باشند.', 'rule', 5, 16, 2),
('semantic-core', 'C-073', 'هر تصمیم در جای خودش گرفته می‌شود.', 'rule', 1, 17, 2),
('semantic-core', 'C-074', 'تصمیم‌های جزئی نباید به قانون اساسی منتقل شوند.', 'rule', 1, 17, 2),
('semantic-core', 'C-075', 'تصمیم‌های بنیادین نباید به پیاده‌سازی منتقل شوند.', 'rule', 1, 17, 2),
('semantic-core', 'C-076', 'قرار دادن ابزار و فناوری در قانون اساسی ممنوع است.', 'forbidden', 1, 17, 2),
('semantic-core', 'C-077', 'پنهان‌کردن عدم قطعیت از کاربر ممنوع است.', 'forbidden', 1, 17, 2),
('semantic-core', 'C-078', 'سیستم باید بتواند بگوید چه می‌داند.', 'requirement', 1, 17, 2),
('semantic-core', 'C-079', 'سیستم باید بتواند بگوید در چه شرایطی معتبر است.', 'requirement', 1, 17, 2),
('semantic-core', 'C-080', 'سیستم باید بتواند بگوید چه چیزهایی هنوز ممکن است.', 'requirement', 1, 17, 2),
('semantic-core', 'C-081', 'سیستم باید بتواند بگوید کدام آزمون بیشترین کاهش ابهام را می‌دهد.', 'requirement', 1, 17, 2);
